
model_parameters:
  onnx_model: '../ONNX/yolo11s.onnx'
  march: "bayes-e"
  layer_out_dump: False
  working_dir: 'bpu_model_output'
  output_model_file_prefix: 'yolo11s_detect_bayese_640x640_nv12'
input_parameters:
  input_name: ""
  input_type_rt: 'nv12'
  input_type_train: 'rgb'
  input_layout_train: 'NCHW'
  norm_type: 'data_scale'
  scale_value: 0.003921568627451
calibration_parameters:
  cal_data_dir: '../calibration_data_rgb_f32_coco_640'
  cal_data_type: 'float32'
  calibration_type: 'default'
  optimization: set_Softmax_input_int8,set_Softmax_output_int8
compiler_parameters:
  jobs: 2
  compile_mode: 'latency'
  debug: true
  optimize_level: 'O3'
