import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import type { Catalog, CatalogSourceRecord, CatalogSummary } from "./catalog/types";

/** File name of the data payload inside an artifact directory. */
export const CATALOG_FILE = "catalog.json";
/** File name of the checksum and provenance contract that describes the payload. */
export const CATALOG_METADATA_FILE = "catalog.meta.json";

/**
 * The published contract between the model repository and any consumer.
 * `sha256` is taken over the exact bytes of `catalog.json`, so a consumer can
 * reject a snapshot that was edited, truncated, or generated by another tool.
 */
export interface CatalogArtifactMetadata {
  schema_version: 1;
  /** Payload file name inside the artifact directory. */
  payload: string;
  /** Stable identifier for this data revision. */
  catalog_version: string;
  release_tag: string;
  platform_tags: Record<string, string>;
  summary: CatalogSummary;
  sources: Record<string, CatalogSourceRecord>;
  sha256: string;
  bytes: number;
  generator: { name: string; path: string };
}

/** Serialises the catalog deterministically: the bytes are the checksummed payload. */
export function serializeCatalog(catalog: Catalog): string {
  return `${JSON.stringify(catalog, null, 2)}\n`;
}

export function sha256Of(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

export function metadataFor(catalog: Catalog, serialized: string, generatorPath: string): CatalogArtifactMetadata {
  const platformTags = { ...(catalog.release.platform_tags ?? {}) };
  return {
    schema_version: 1,
    payload: CATALOG_FILE,
    catalog_version: catalog.release.catalog_version ?? catalog.release.tag,
    release_tag: catalog.release.tag,
    platform_tags: platformTags,
    summary: catalog.summary,
    sources: catalog.sources ?? {},
    sha256: sha256Of(serialized),
    bytes: Buffer.byteLength(serialized, "utf8"),
    generator: { name: "catalog-publisher", path: generatorPath }
  };
}

export interface WritableArtifact {
  catalogPath: string;
  metadataPath: string;
  metadata: CatalogArtifactMetadata;
}

/** Writes `catalog.json` and its `catalog.meta.json` contract into a directory. */
export async function writeCatalogArtifact(
  catalog: Catalog,
  outputDirectory: string,
  generatorPath: string
): Promise<WritableArtifact> {
  const serialized = serializeCatalog(catalog);
  const metadata = metadataFor(catalog, serialized, generatorPath);
  const catalogPath = resolve(outputDirectory, CATALOG_FILE);
  const metadataPath = resolve(outputDirectory, CATALOG_METADATA_FILE);
  await mkdir(dirname(catalogPath), { recursive: true });
  await writeFile(catalogPath, serialized, "utf8");
  await writeFile(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`, "utf8");
  return { catalogPath, metadataPath, metadata };
}

/**
 * Verifies a payload against a metadata contract. Every consumer — the local
 * import command, the documentation build, and the release check — uses this
 * single implementation so a checksum mismatch always fails loudly.
 */
export function verifyArtifact(payload: string, metadata: CatalogArtifactMetadata): void {
  if (metadata.schema_version !== 1) {
    throw new Error(`Unsupported catalog metadata schema_version: ${metadata.schema_version}`);
  }
  const actual = sha256Of(payload);
  if (actual !== metadata.sha256) {
    throw new Error(
      `Catalog checksum mismatch: catalog.meta.json declares ${metadata.sha256} but the payload hashes to ${actual}`
    );
  }
  const bytes = Buffer.byteLength(payload, "utf8");
  if (bytes !== metadata.bytes) {
    throw new Error(`Catalog size mismatch: catalog.meta.json declares ${metadata.bytes} bytes but the payload is ${bytes}`);
  }
  let parsed: Catalog;
  try {
    parsed = JSON.parse(payload) as Catalog;
  } catch (error) {
    throw new Error(`Catalog payload is not valid JSON: ${(error as Error).message}`);
  }
  const version = parsed.release?.catalog_version ?? parsed.release?.tag;
  if (version !== metadata.catalog_version) {
    throw new Error(
      `Catalog version mismatch: catalog.meta.json declares ${metadata.catalog_version} but the payload carries ${version}`
    );
  }
}

/** Reads and verifies an artifact directory. */
export async function readVerifiedArtifact(directory: string): Promise<{ metadata: CatalogArtifactMetadata; payload: string }> {
  const metadataText = await readFile(resolve(directory, CATALOG_METADATA_FILE), "utf8");
  const metadata = JSON.parse(metadataText) as CatalogArtifactMetadata;
  const payload = await readFile(resolve(directory, metadata.payload ?? CATALOG_FILE), "utf8");
  verifyArtifact(payload, metadata);
  return { metadata, payload };
}
