model_parameters:
  onnx_model: './mobile_sam_image_encoder_norm_512_op11.onnx'
  march: 'bayes-e'
  layer_out_dump: False
  working_dir: 'bpu_model_output_norm_512_allint16'
  output_model_file_prefix: 'mobile_sam_image_encoder_norm_512x512_allint16'
  node_info: {
  "/image_encoder/patch_embed/seq/seq.1/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/blocks.0/act1/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/blocks.0/act2/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/blocks.0/act3/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/blocks.1/act1/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/blocks.1/act2/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/blocks.1/act3/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/downsample/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.0/downsample/act_1/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean_/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.0/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean_/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.1/blocks.1/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.1/downsample/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.1/downsample/act_1/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean_/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.0/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean_/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.1/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean_/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.2/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean_/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.3/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean_/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.4/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean_/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.2/blocks.5/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/downsample/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.2/downsample/act_1/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean_/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.0/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean_output_0_reshape_transpose_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean_/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean_output_0_reshape_Transpose": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean_output_0_Reshape_0": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/attn/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/mlp/norm/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/mlp/norm/Sub": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/mlp/norm/Pow": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/mlp/norm/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/mlp/norm/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/mlp/norm/Div_mul": {'ON': 'CPU'},
  "/image_encoder/layers.3/blocks.1/mlp/act/Mul_1": {'ON': 'BPU', 'InputType': 'int16', 'OutputType': 'int16'},
  "/image_encoder/neck/neck.0/Conv": {'ON': 'CPU'},
  "/image_encoder/neck/neck.1/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/neck/neck.1/Sub": {'ON': 'CPU'},
  "/image_encoder/neck/neck.1/Pow": {'ON': 'CPU'},
  "/image_encoder/neck/neck.1/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/neck/neck.1/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/neck/neck.1/Div_mul": {'ON': 'CPU'},
  "/image_encoder/neck/neck.1/Mul": {'ON': 'CPU'},
  "/image_encoder/neck/neck.2/Conv": {'ON': 'CPU'},
  "/image_encoder/neck/neck.3/ReduceMean": {'ON': 'CPU'},
  "/image_encoder/neck/neck.3/Sub": {'ON': 'CPU'},
  "/image_encoder/neck/neck.3/Pow": {'ON': 'CPU'},
  "/image_encoder/neck/neck.3/ReduceMean_1": {'ON': 'CPU'},
  "/image_encoder/neck/neck.3/Div_reciprocal": {'ON': 'CPU'},
  "/image_encoder/neck/neck.3/Div_mul": {'ON': 'CPU'},
  "/image_encoder/neck/neck.3/Mul": {'ON': 'CPU'}
  }

input_parameters:
  input_name: 'normalized_images'
  input_type_rt: 'featuremap'
  input_type_train: 'featuremap'
  input_layout_train: 'NCHW'
  input_layout_rt: 'NCHW'
  input_shape: '1x3x512x512'
  norm_type: 'no_preprocess'

calibration_parameters:
  cal_data_dir: './calibration_data_norm_512'
  cal_data_type: 'float32'
  optimization: 'set_all_nodes_int16'
  calibration_type: 'max'

compiler_parameters:
  jobs: 8
  compile_mode: 'latency'
  debug: false
  optimize_level: 'O3'

