model_parameters:
  onnx_model: /Users/Max/Workspace/company/development/RDK_MODEL_ZOO/.coordination/yoloe-prepare-real-20260928/s100-11s/source/model.onnx
  march: nash-e
  working_dir: /Users/Max/Workspace/company/development/RDK_MODEL_ZOO/.coordination/yoloe-prepare-real-20260928/s100-11s/compiler_output
  output_model_file_prefix: yoloe_11s_seg_pf_nashe_640x640_nv12_float
input_parameters:
  input_name: images
  input_shape: 1x3x640x640
  input_type_rt: nv12
  input_type_train: rgb
  input_layout_train: NCHW
  scale_value: 0.00392156862745098
  norm_type: data_scale
calibration_parameters:
  cal_data_dir: /Users/Max/Workspace/company/development/RDK_MODEL_ZOO/.coordination/yoloe-prepare-real-20260928/s100-11s/calibration
  cal_data_type: float32
  calibration_type: default
  quant_config:
    op_config:
      softmax:
        qtype: int8
compiler_parameters:
  jobs: 15
  compile_mode: latency
  core_num: 1
  extra_params:
    input_no_padding: true
    output_no_padding: true
  debug: true
  advice: 1
  optimize_level: O2
