model_parameters:
  onnx_model: /Users/Max/Workspace/company/development/RDK_MODEL_ZOO/.coordination/yoloe-prepare-real-20260928/s100-26l/source/model.onnx
  march: nash-e
  working_dir: /Users/Max/Workspace/company/development/RDK_MODEL_ZOO/.coordination/yoloe-prepare-real-20260928/s100-26l/compiler_output
  output_model_file_prefix: yoloe_26l_seg_pf_nashe_640x640_nv12_float
input_parameters:
  input_name: images
  input_shape: 1x3x640x640
  input_type_rt: nv12
  input_type_train: rgb
  input_layout_train: NCHW
  scale_value: 0.00392156862745098
calibration_parameters:
  cal_data_dir: /Users/Max/Workspace/company/development/RDK_MODEL_ZOO/.coordination/yoloe-prepare-real-20260928/s100-26l/calibration
  cal_data_type: float32
  calibration_type: kl
  quant_config:
    model_config:
      all_node_type: int8
compiler_parameters:
  jobs: 4
  compile_mode: latency
  core_num: 1
  extra_params:
    input_no_padding: true
    output_no_padding: false
  debug: true
  optimize_level: O2
