# Copyright (c) 2026 D-Robotics Corporation
# SPDX-License-Identifier: Apache-2.0
"""Lazy SDK transport; no activation, calibration, timing or rendering."""

from utils.py_utils.single_array_runner import (
    SingleArrayRunner,
    RuntimeUnavailableError,
)
from utils.py_utils.platforms import require_execution_target
from samples.vision.yolo26_depth.runtime.python.model_binding import bind_model


class RuntimeModelRunner(SingleArrayRunner):
    def __init__(self, selection, *, runtime_factory=None, runtime=None):
        if selection.converted_model and runtime_factory is None and runtime is None:
            runtime_factory = _converted_factory(selection)
        super().__init__(
            selection,
            binding_loader=bind_model,
            physical_inputs=lambda b: (
                {n: (b.metadata.input_shapes[n], "uint8") for n in (b.input_name, b.uv_name)}
                if b.uv_name is not None else
                {b.input_name: (((1, 3, 768, 768), "float32")
                    if b.selection.profile == "lite" else ((768 * 768 * 3 // 2,), "uint8"))}
            ),
            task_name="YOLO26 Depth",
            runtime_factory=runtime_factory,
            runtime=runtime,
            execution_target_gate=require_execution_target,
        )


__all__ = ["RuntimeModelRunner", "RuntimeUnavailableError"]


def _converted_factory(selection):
    """Explicit custom-artifact loader; target gating is never optional here.

    The referenced published asset selects only the declared tensor contract.
    Its publisher digest cannot certify user-generated bytes.
    """

    def create(path):
        require_execution_target(selection.target)
        if (
            not selection.model_path.is_file()
            or selection.model_path.stat().st_size == 0
        ):
            raise ValueError(
                f"Missing or empty converted model: {selection.model_path}"
            )
        try:
            from hbm_runtime import HB_HBMRuntime
        except ImportError as exc:
            raise RuntimeUnavailableError(
                "hbm_runtime is required on the selected board"
            ) from exc
        return HB_HBMRuntime(path)

    return create
