# Copyright (c) 2024 D-Robotics.All Rights Reserved.
#
# The material in this file is confidential and contains trade secrets
# of D-Robotics Inc. This is proprietary information owned by
# D-Robotics Inc. No part of this work may be disclosed,
# reproduced, copied, transmitted, or used in any way for any purpose,
# without the express written permission of D-Robotics Inc.



model_parameters:
  onnx_model: '../../../01_common/model_zoo/mapper/classification/FastViT/fastvit_s12.onnx'
  march: "bayes-e"
  layer_out_dump: False
  working_dir: 'FastViT_224x224_nv12_mix'
  output_model_file_prefix: 'FastViT_224x224_nv12'
  

  node_info: {
    "/patch_embed/patch_embed.0/activation/Mul_1": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/patch_embed/patch_embed.1/activation/Mul_1": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/patch_embed/patch_embed.2/activation/Mul_1": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/network.2/network.2.0/convffn/ff2/Conv": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    },
    "/gap/GlobalAveragePool": {
      'ON': 'BPU',
      'InputType': 'int16',
      'OutputType': 'int16'
    }
  }


input_parameters:
  input_name: ""
  input_type_rt: 'nv12'
  input_type_train: 'rgb'
  input_layout_train: 'NCHW'
  input_shape: ''
  norm_type: 'data_mean_and_scale'
  mean_value: 123.675 116.28 103.53
  scale_value: 0.01712475 0.017507 0.01742919


calibration_parameters:
  cal_data_dir: './calibration_data_rgb_f32'
  cal_data_type: 'float32'
  calibration_type: 'default'

compiler_parameters:
  compile_mode: 'latency'
  debug: False
  optimize_level: 'O3'
  
